# Generated by Django 4.1.2 on 2023-09-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usercore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='place mail adress')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='name')),
                ('surname', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='surname')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='uploads/user/', verbose_name='pic1')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='uploads/user/', verbose_name='pic2')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='uploads/user/', verbose_name='pic3')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='uploads/user/', verbose_name='pic4')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='uploads/user/', verbose_name='pic5')),
                ('firstLogin', models.BooleanField(default=True, verbose_name='firstLogin')),
                ('gender', models.CharField(blank=True, choices=[('Kadın', 'Kadın'), ('Erkek', 'Erkek'), ('Diğer', 'Diğer')], default=None, max_length=10, null=True)),
                ('phone', models.IntegerField(unique=True, verbose_name='phone')),
                ('money', models.IntegerField(blank=True, null=True, verbose_name='money')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
