# Generated by Django 4.1.2 on 2023-09-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_communities'),
        ('account', '0003_usercore_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercore',
            name='wantToKnow',
        ),
        migrations.AddField(
            model_name='usercore',
            name='wantToKnowComm',
            field=models.ManyToManyField(related_name='wanttoknowc+', to='activities.communities', verbose_name='want to know'),
        ),
        migrations.AddField(
            model_name='usercore',
            name='wantToKnowHash',
            field=models.ManyToManyField(related_name='wanttoknowh+', to='activities.hashtags', verbose_name='want to know'),
        ),
        migrations.AddField(
            model_name='usercore',
            name='wantToKnowPlac',
            field=models.ManyToManyField(related_name='wanttoknowp+', to='activities.places', verbose_name='want to know'),
        ),
    ]
