# Generated by Django 4.1.2 on 2023-09-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_rename_communitys_activities_community_and_more'),
        ('account', '0004_remove_usercore_wanttoknow_usercore_wanttoknowcomm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercore',
            name='knowAct',
            field=models.ManyToManyField(related_name='wanttoknowp+', to='activities.activities', verbose_name='want to know'),
        ),
    ]
