# Generated by Django 4.1.2 on 2023-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_rename_communitys_activities_community_and_more'),
        ('account', '0005_usercore_knowact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercore',
            name='knowAct',
            field=models.ManyToManyField(related_name='wanttoknowact+', to='activities.activities', verbose_name='want to know'),
        ),
    ]
