# Generated by Django 4.1.2 on 2023-09-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_rename_communitys_activities_community_and_more'),
        ('account', '0006_alter_usercore_knowact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercore',
            name='knowAct',
            field=models.ManyToManyField(blank=True, null=True, related_name='wanttoknowact+', to='activities.activities', verbose_name='want to know'),
        ),
        migrations.AlterField(
            model_name='usercore',
            name='wantToKnowComm',
            field=models.ManyToManyField(blank=True, null=True, related_name='wanttoknowc+', to='activities.communities', verbose_name='want to know'),
        ),
        migrations.AlterField(
            model_name='usercore',
            name='wantToKnowHash',
            field=models.ManyToManyField(blank=True, null=True, related_name='wanttoknowh+', to='activities.hashtags', verbose_name='want to know'),
        ),
        migrations.AlterField(
            model_name='usercore',
            name='wantToKnowPlac',
            field=models.ManyToManyField(blank=True, null=True, related_name='wanttoknowp+', to='activities.places', verbose_name='want to know'),
        ),
    ]
