# Generated by Django 4.1.2 on 2023-09-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_usercore_knowact_alter_usercore_wanttoknowcomm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercore',
            old_name='knowAct',
            new_name='IKnowAct',
        ),
    ]
