# Generated by Django 4.1.2 on 2023-10-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_knowact_usercore_iknowact'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercore',
            name='firebase_messaging_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
