# Generated by Django 4.1.2 on 2023-09-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='place',
            new_name='name',
        ),
    ]
