# Generated by Django 4.1.2 on 2023-09-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_place_places_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='communities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='place')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='uploads/places/', verbose_name='pic')),
            ],
        ),
    ]
