# Generated by Django 4.1.2 on 2023-09-09 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='community',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activities.communities', verbose_name='community'),
            preserve_default=False,
        ),
    ]
