# Generated by Django 4.1.2 on 2023-09-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_rename_community_activities_communitys_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='communitys',
            new_name='community',
        ),
        migrations.RenameField(
            model_name='activities',
            old_name='places',
            new_name='place',
        ),
    ]
