# Generated by Django 4.1.2 on 2023-09-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_rename_communitys_activities_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity',
            field=models.CharField(max_length=50, verbose_name='link'),
        ),
    ]
